// Code generated by protoc-gen-go.
// source: proxy/v1/config/proxy_mesh.proto
// DO NOT EDIT!

package istio_proxy_v1_config

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf1 "github.com/golang/protobuf/ptypes/duration"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type MeshConfig_IngressControllerMode int32

const (
	// Disables Istio ingress controller.
	MeshConfig_OFF MeshConfig_IngressControllerMode = 0
	// Istio ingress controller will act on ingress resources that do not
	// contain any annotation or whose annotations match the value
	// specified in the ingress_class parameter described earlier. Use this
	// mode if Istio ingress controller will be the default ingress
	// controller for the entire kubernetes cluster.
	MeshConfig_DEFAULT MeshConfig_IngressControllerMode = 1
	// Istio ingress controller will only act on ingress resources whose
	// annotations match the value specified in the ingress_class parameter
	// described earlier. Use this mode if Istio ingress controller will be
	// a secondary ingress controller (e.g., in addition to a
	// cloud-provided ingress controller).
	MeshConfig_STRICT MeshConfig_IngressControllerMode = 2
)

var MeshConfig_IngressControllerMode_name = map[int32]string{
	0: "OFF",
	1: "DEFAULT",
	2: "STRICT",
}
var MeshConfig_IngressControllerMode_value = map[string]int32{
	"OFF":     0,
	"DEFAULT": 1,
	"STRICT":  2,
}

func (x MeshConfig_IngressControllerMode) String() string {
	return proto.EnumName(MeshConfig_IngressControllerMode_name, int32(x))
}
func (MeshConfig_IngressControllerMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor5, []int{1, 0}
}

type MeshConfig_AuthPolicy int32

const (
	// Do not encrypt Envoy to Envoy traffic.
	MeshConfig_NONE MeshConfig_AuthPolicy = 0
	// Envoy to Envoy traffic is wrapped into mutual TLS connections.
	MeshConfig_MUTUAL_TLS MeshConfig_AuthPolicy = 1
)

var MeshConfig_AuthPolicy_name = map[int32]string{
	0: "NONE",
	1: "MUTUAL_TLS",
}
var MeshConfig_AuthPolicy_value = map[string]int32{
	"NONE":       0,
	"MUTUAL_TLS": 1,
}

func (x MeshConfig_AuthPolicy) String() string {
	return proto.EnumName(MeshConfig_AuthPolicy_name, int32(x))
}
func (MeshConfig_AuthPolicy) EnumDescriptor() ([]byte, []int) { return fileDescriptor5, []int{1, 1} }

// ProxyConfig defines variables for individual Envoy instances.
type ProxyConfig struct {
	// Path to the generated configuration file directory.
	// Proxy agent generates the actual configuration and stores it in this directory.
	ConfigPath string `protobuf:"bytes,1,opt,name=config_path,json=configPath" json:"config_path,omitempty"`
	// Path to the proxy binary
	BinaryPath string `protobuf:"bytes,2,opt,name=binary_path,json=binaryPath" json:"binary_path,omitempty"`
	// Service cluster defines the name for the service_cluster that is
	// shared by all Envoy instances. This setting corresponds to
	// _--service-cluster_ flag in Envoy.  In a typical Envoy deployment, the
	// _service-cluster_ flag is used to identify the caller, for
	// source-based routing scenarios.
	//
	// Since Istio does not assign a local service/service version to each
	// Envoy instance, the name is same for all of them.  However, the
	// source/caller's identity (e.g., IP address) is encoded in the
	// _--service-node_ flag when launching Envoy.  When the RDS service
	// receives API calls from Envoy, it uses the value of the _service-node_
	// flag to compute routes that are relative to the service instances
	// located at that IP address.
	ServiceCluster string `protobuf:"bytes,3,opt,name=service_cluster,json=serviceCluster" json:"service_cluster,omitempty"`
	// The time in seconds that Envoy will drain connections during a hot
	// restart. MUST be >=1s (e.g., _1s/1m/1h_)
	DrainDuration *google_protobuf1.Duration `protobuf:"bytes,4,opt,name=drain_duration,json=drainDuration" json:"drain_duration,omitempty"`
	// The time in seconds that Envoy will wait before shutting down the
	// parent process during a hot restart. MUST be >=1s (e.g., _1s/1m/1h_).
	// MUST BE greater than _drain_duration_ parameter.
	ParentShutdownDuration *google_protobuf1.Duration `protobuf:"bytes,5,opt,name=parent_shutdown_duration,json=parentShutdownDuration" json:"parent_shutdown_duration,omitempty"`
	// Address of the discovery service exposing xDS (e.g. _istio-pilot:8080_).
	DiscoveryAddress string `protobuf:"bytes,6,opt,name=discovery_address,json=discoveryAddress" json:"discovery_address,omitempty"`
	// Polling interval for service discovery (used by EDS, CDS, LDS, but not RDS). (MUST BE >=1ms)
	DiscoveryRefreshDelay *google_protobuf1.Duration `protobuf:"bytes,7,opt,name=discovery_refresh_delay,json=discoveryRefreshDelay" json:"discovery_refresh_delay,omitempty"`
	// Address of the Zipkin service (e.g. _zipkin:9411_).
	ZipkinAddress string `protobuf:"bytes,8,opt,name=zipkin_address,json=zipkinAddress" json:"zipkin_address,omitempty"`
	// Connection timeout used by Envoy for supporting services. (MUST BE >=1ms)
	ConnectTimeout *google_protobuf1.Duration `protobuf:"bytes,9,opt,name=connect_timeout,json=connectTimeout" json:"connect_timeout,omitempty"`
	// IP Address and Port of a statsd UDP listener (e.g. _10.75.241.127:9125_).
	StatsdUdpAddress string `protobuf:"bytes,10,opt,name=statsd_udp_address,json=statsdUdpAddress" json:"statsd_udp_address,omitempty"`
	// Port on which Envoy should listen for administrative commands.
	ProxyAdminPort int32 `protobuf:"varint,11,opt,name=proxy_admin_port,json=proxyAdminPort" json:"proxy_admin_port,omitempty"`
	// The availability zone where this Envoy instance is running. When running
	// Envoy as a sidecar in Kubernetes, this flag must be one of the availability
	// zones assigned to a node using failure-domain.beta.kubernetes.io/zone annotation.
	AvailabilityZone string `protobuf:"bytes,12,opt,name=availability_zone,json=availabilityZone" json:"availability_zone,omitempty"`
}

func (m *ProxyConfig) Reset()                    { *m = ProxyConfig{} }
func (m *ProxyConfig) String() string            { return proto.CompactTextString(m) }
func (*ProxyConfig) ProtoMessage()               {}
func (*ProxyConfig) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{0} }

func (m *ProxyConfig) GetConfigPath() string {
	if m != nil {
		return m.ConfigPath
	}
	return ""
}

func (m *ProxyConfig) GetBinaryPath() string {
	if m != nil {
		return m.BinaryPath
	}
	return ""
}

func (m *ProxyConfig) GetServiceCluster() string {
	if m != nil {
		return m.ServiceCluster
	}
	return ""
}

func (m *ProxyConfig) GetDrainDuration() *google_protobuf1.Duration {
	if m != nil {
		return m.DrainDuration
	}
	return nil
}

func (m *ProxyConfig) GetParentShutdownDuration() *google_protobuf1.Duration {
	if m != nil {
		return m.ParentShutdownDuration
	}
	return nil
}

func (m *ProxyConfig) GetDiscoveryAddress() string {
	if m != nil {
		return m.DiscoveryAddress
	}
	return ""
}

func (m *ProxyConfig) GetDiscoveryRefreshDelay() *google_protobuf1.Duration {
	if m != nil {
		return m.DiscoveryRefreshDelay
	}
	return nil
}

func (m *ProxyConfig) GetZipkinAddress() string {
	if m != nil {
		return m.ZipkinAddress
	}
	return ""
}

func (m *ProxyConfig) GetConnectTimeout() *google_protobuf1.Duration {
	if m != nil {
		return m.ConnectTimeout
	}
	return nil
}

func (m *ProxyConfig) GetStatsdUdpAddress() string {
	if m != nil {
		return m.StatsdUdpAddress
	}
	return ""
}

func (m *ProxyConfig) GetProxyAdminPort() int32 {
	if m != nil {
		return m.ProxyAdminPort
	}
	return 0
}

func (m *ProxyConfig) GetAvailabilityZone() string {
	if m != nil {
		return m.AvailabilityZone
	}
	return ""
}

// MeshConfig defines mesh-wide variables shared by all Envoy instances in the
// Istio service mesh.
type MeshConfig struct {
	// Address of the egress Envoy service (e.g. _istio-egress:80_).
	EgressProxyAddress string `protobuf:"bytes,1,opt,name=egress_proxy_address,json=egressProxyAddress" json:"egress_proxy_address,omitempty"`
	// Address of the mixer service (e.g. _istio-mixer:9090_).
	// Empty value disables Mixer checks and telemetry.
	MixerAddress string `protobuf:"bytes,2,opt,name=mixer_address,json=mixerAddress" json:"mixer_address,omitempty"`
	// Disable policy checks by the mixer service. Metrics will still be
	// reported to the mixer for HTTP requests and TCP connections. Default
	// is false, i.e. mixer policy check is enabled by default.
	DisablePolicyChecks bool `protobuf:"varint,3,opt,name=disable_policy_checks,json=disablePolicyChecks" json:"disable_policy_checks,omitempty"`
	// Port on which Envoy should listen for incoming connections from
	// other services.
	ProxyListenPort int32 `protobuf:"varint,4,opt,name=proxy_listen_port,json=proxyListenPort" json:"proxy_listen_port,omitempty"`
	// Port on which Envoy should listen for HTTP PROXY requests if set.
	ProxyHttpPort int32 `protobuf:"varint,5,opt,name=proxy_http_port,json=proxyHttpPort" json:"proxy_http_port,omitempty"`
	// Connection timeout used by Envoy. (MUST BE >=1ms)
	ConnectTimeout *google_protobuf1.Duration `protobuf:"bytes,6,opt,name=connect_timeout,json=connectTimeout" json:"connect_timeout,omitempty"`
	// Class of ingress resources to be processed by Istio ingress
	// controller.  This corresponds to the value of
	// "kubernetes.io/ingress.class" annotation.
	IngressClass string `protobuf:"bytes,7,opt,name=ingress_class,json=ingressClass" json:"ingress_class,omitempty"`
	// Name of the kubernetes service used for the istio ingress controller.
	IngressService string `protobuf:"bytes,8,opt,name=ingress_service,json=ingressService" json:"ingress_service,omitempty"`
	// Defines whether to use Istio ingress controller for annotated or all ingress resources.
	IngressControllerMode MeshConfig_IngressControllerMode `protobuf:"varint,9,opt,name=ingress_controller_mode,json=ingressControllerMode,enum=istio.proxy.v1.config.MeshConfig_IngressControllerMode" json:"ingress_controller_mode,omitempty"`
	// Authentication policy defines the global switch to control authentication
	// for Envoy-to-Envoy communication.
	AuthPolicy MeshConfig_AuthPolicy `protobuf:"varint,10,opt,name=auth_policy,json=authPolicy,enum=istio.proxy.v1.config.MeshConfig_AuthPolicy" json:"auth_policy,omitempty"`
	// Polling interval for RDS (MUST BE >=1ms)
	RdsRefreshDelay *google_protobuf1.Duration `protobuf:"bytes,11,opt,name=rds_refresh_delay,json=rdsRefreshDelay" json:"rds_refresh_delay,omitempty"`
	// Flag to control generation of trace spans and request IDs.
	// Requires a trace span collector defined in the proxy configuration.
	EnableTracing bool `protobuf:"varint,12,opt,name=enable_tracing,json=enableTracing" json:"enable_tracing,omitempty"`
	// File address for the proxy access log (e.g. /dev/stdout).
	// Empty value disables access logging.
	AccessLogFile string `protobuf:"bytes,13,opt,name=access_log_file,json=accessLogFile" json:"access_log_file,omitempty"`
	// Default proxy config used by the proxy injection mechanism operating in the mesh
	// (e.g. Kubernetes admission controller)
	// In case of Kubernetes, the proxy config is applied once during the injection process,
	// and remain constant for the duration of the pod. The rest of the mesh config can be changed
	// at runtime and config gets distributed dynamically.
	DefaultConfig *ProxyConfig `protobuf:"bytes,14,opt,name=default_config,json=defaultConfig" json:"default_config,omitempty"`
}

func (m *MeshConfig) Reset()                    { *m = MeshConfig{} }
func (m *MeshConfig) String() string            { return proto.CompactTextString(m) }
func (*MeshConfig) ProtoMessage()               {}
func (*MeshConfig) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{1} }

func (m *MeshConfig) GetEgressProxyAddress() string {
	if m != nil {
		return m.EgressProxyAddress
	}
	return ""
}

func (m *MeshConfig) GetMixerAddress() string {
	if m != nil {
		return m.MixerAddress
	}
	return ""
}

func (m *MeshConfig) GetDisablePolicyChecks() bool {
	if m != nil {
		return m.DisablePolicyChecks
	}
	return false
}

func (m *MeshConfig) GetProxyListenPort() int32 {
	if m != nil {
		return m.ProxyListenPort
	}
	return 0
}

func (m *MeshConfig) GetProxyHttpPort() int32 {
	if m != nil {
		return m.ProxyHttpPort
	}
	return 0
}

func (m *MeshConfig) GetConnectTimeout() *google_protobuf1.Duration {
	if m != nil {
		return m.ConnectTimeout
	}
	return nil
}

func (m *MeshConfig) GetIngressClass() string {
	if m != nil {
		return m.IngressClass
	}
	return ""
}

func (m *MeshConfig) GetIngressService() string {
	if m != nil {
		return m.IngressService
	}
	return ""
}

func (m *MeshConfig) GetIngressControllerMode() MeshConfig_IngressControllerMode {
	if m != nil {
		return m.IngressControllerMode
	}
	return MeshConfig_OFF
}

func (m *MeshConfig) GetAuthPolicy() MeshConfig_AuthPolicy {
	if m != nil {
		return m.AuthPolicy
	}
	return MeshConfig_NONE
}

func (m *MeshConfig) GetRdsRefreshDelay() *google_protobuf1.Duration {
	if m != nil {
		return m.RdsRefreshDelay
	}
	return nil
}

func (m *MeshConfig) GetEnableTracing() bool {
	if m != nil {
		return m.EnableTracing
	}
	return false
}

func (m *MeshConfig) GetAccessLogFile() string {
	if m != nil {
		return m.AccessLogFile
	}
	return ""
}

func (m *MeshConfig) GetDefaultConfig() *ProxyConfig {
	if m != nil {
		return m.DefaultConfig
	}
	return nil
}

func init() {
	proto.RegisterType((*ProxyConfig)(nil), "istio.proxy.v1.config.ProxyConfig")
	proto.RegisterType((*MeshConfig)(nil), "istio.proxy.v1.config.MeshConfig")
	proto.RegisterEnum("istio.proxy.v1.config.MeshConfig_IngressControllerMode", MeshConfig_IngressControllerMode_name, MeshConfig_IngressControllerMode_value)
	proto.RegisterEnum("istio.proxy.v1.config.MeshConfig_AuthPolicy", MeshConfig_AuthPolicy_name, MeshConfig_AuthPolicy_value)
}

func init() { proto.RegisterFile("proxy/v1/config/proxy_mesh.proto", fileDescriptor5) }

var fileDescriptor5 = []byte{
	// 770 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xcf, 0x6f, 0xdb, 0x36,
	0x14, 0xae, 0xdb, 0xfc, 0x7c, 0x8e, 0x14, 0x87, 0x5b, 0x56, 0x6d, 0x87, 0x2d, 0x70, 0xb1, 0x2e,
	0xd8, 0x0a, 0x79, 0xcd, 0x0e, 0xc3, 0x6e, 0xf3, 0x9c, 0x18, 0x0b, 0x60, 0xb7, 0x9e, 0x6c, 0x5f,
	0x76, 0x21, 0x68, 0x91, 0xb6, 0x88, 0xca, 0xa2, 0x40, 0x52, 0x5e, 0xdd, 0xdb, 0xfe, 0xf2, 0x0d,
	0xe2, 0x93, 0x94, 0x20, 0xf0, 0x60, 0xec, 0x26, 0x7e, 0xef, 0xfb, 0xf8, 0x7e, 0x7d, 0x14, 0x5c,
	0xe5, 0x5a, 0x7d, 0xdc, 0xf6, 0x36, 0x6f, 0x7b, 0xb1, 0xca, 0x96, 0x72, 0xd5, 0x73, 0x67, 0xba,
	0x16, 0x26, 0x09, 0x73, 0xad, 0xac, 0x22, 0x97, 0xd2, 0x58, 0xa9, 0x42, 0x87, 0x87, 0x9b, 0xb7,
	0x21, 0xf2, 0xbe, 0xfa, 0x7a, 0xa5, 0xd4, 0x2a, 0x15, 0x3d, 0x47, 0x5a, 0x14, 0xcb, 0x1e, 0x2f,
	0x34, 0xb3, 0x52, 0x65, 0x28, 0xeb, 0xfe, 0x73, 0x00, 0xed, 0x49, 0xa9, 0x19, 0x38, 0x3e, 0xf9,
	0x06, 0xda, 0xa8, 0xa4, 0x39, 0xb3, 0x49, 0xd0, 0xba, 0x6a, 0x5d, 0x9f, 0x46, 0x80, 0xd0, 0x84,
	0xd9, 0xa4, 0x24, 0x2c, 0x64, 0xc6, 0xf4, 0x16, 0x09, 0xcf, 0x91, 0x80, 0x90, 0x23, 0x7c, 0x07,
	0xe7, 0x46, 0xe8, 0x8d, 0x8c, 0x05, 0x8d, 0xd3, 0xc2, 0x58, 0xa1, 0x83, 0x17, 0x8e, 0xe4, 0x57,
	0xf0, 0x00, 0x51, 0xf2, 0x2b, 0xf8, 0x5c, 0x33, 0x99, 0xd1, 0xba, 0xa4, 0xe0, 0xe0, 0xaa, 0x75,
	0xdd, 0xbe, 0xf9, 0x32, 0xc4, 0x9a, 0xc3, 0xba, 0xe6, 0xf0, 0xb6, 0x22, 0x44, 0x9e, 0x13, 0xd4,
	0x47, 0x32, 0x85, 0x20, 0x67, 0x5a, 0x64, 0x96, 0x9a, 0xa4, 0xb0, 0x5c, 0xfd, 0xf5, 0xe8, 0xae,
	0xc3, 0x7d, 0x77, 0x7d, 0x81, 0xd2, 0x69, 0xa5, 0x6c, 0x2e, 0xfd, 0x01, 0x2e, 0xb8, 0x34, 0xb1,
	0xda, 0x08, 0xbd, 0xa5, 0x8c, 0x73, 0x2d, 0x8c, 0x09, 0x8e, 0x5c, 0x07, 0x9d, 0x26, 0xd0, 0x47,
	0x9c, 0xfc, 0x01, 0x2f, 0x1f, 0xc8, 0x5a, 0x2c, 0xb5, 0x30, 0x09, 0xe5, 0x22, 0x65, 0xdb, 0xe0,
	0x78, 0x5f, 0x01, 0x97, 0x8d, 0x32, 0x42, 0xe1, 0x6d, 0xa9, 0x23, 0xdf, 0x82, 0xff, 0x49, 0xe6,
	0x1f, 0x64, 0xd6, 0x24, 0x3f, 0x71, 0xc9, 0x3d, 0x44, 0xeb, 0xcc, 0xbf, 0xc1, 0x79, 0xac, 0xb2,
	0x4c, 0xc4, 0x96, 0x5a, 0xb9, 0x16, 0xaa, 0xb0, 0xc1, 0xe9, 0xbe, 0x8c, 0x7e, 0xa5, 0x98, 0xa1,
	0x80, 0xbc, 0x01, 0x62, 0x2c, 0xb3, 0x86, 0xd3, 0x82, 0xe7, 0x4d, 0x3a, 0xc0, 0x5e, 0x31, 0x32,
	0xe7, 0x79, 0x9d, 0xf1, 0x1a, 0x3a, 0xe8, 0x3a, 0xc6, 0xd7, 0x32, 0xa3, 0xb9, 0xd2, 0x36, 0x68,
	0x5f, 0xb5, 0xae, 0x0f, 0x23, 0xdf, 0xe1, 0xfd, 0x12, 0x9e, 0x28, 0x6d, 0xcb, 0x11, 0xb2, 0x0d,
	0x93, 0x29, 0x5b, 0xc8, 0x54, 0xda, 0x2d, 0xfd, 0xa4, 0x32, 0x11, 0x9c, 0xe1, 0xb5, 0x8f, 0x03,
	0x7f, 0xaa, 0x4c, 0x74, 0xff, 0x3e, 0x06, 0x18, 0x0b, 0x93, 0x54, 0x06, 0xfc, 0x11, 0x3e, 0x17,
	0xab, 0x32, 0x1f, 0xad, 0x93, 0x61, 0x55, 0xe8, 0x44, 0x82, 0xb1, 0x09, 0xe6, 0xc3, 0xba, 0x5e,
	0x81, 0xb7, 0x96, 0x1f, 0x85, 0x6e, 0xa8, 0xe8, 0xc9, 0x33, 0x07, 0xd6, 0xa4, 0x1b, 0x28, 0xc7,
	0xcd, 0x16, 0xa9, 0xa0, 0xb9, 0x4a, 0x65, 0xbc, 0xa5, 0x71, 0x22, 0xe2, 0x0f, 0xc6, 0x79, 0xf3,
	0x24, 0xfa, 0xac, 0x0a, 0x4e, 0x5c, 0x6c, 0xe0, 0x42, 0xe4, 0x7b, 0xb8, 0xc0, 0x1a, 0x52, 0x69,
	0xac, 0xa8, 0x3a, 0x3e, 0x70, 0x1d, 0x9f, 0xbb, 0xc0, 0xc8, 0xe1, 0xae, 0xe5, 0xd7, 0x80, 0x10,
	0x4d, 0xac, 0xcd, 0x91, 0x79, 0xe8, 0x98, 0x9e, 0x83, 0x7f, 0xb7, 0x36, 0x77, 0xbc, 0x1d, 0x6b,
	0x3b, 0xfa, 0xbf, 0x6b, 0x7b, 0x05, 0x9e, 0xcc, 0x70, 0x46, 0x71, 0xca, 0x8c, 0x71, 0x56, 0x3b,
	0x8d, 0xce, 0x2a, 0x70, 0x50, 0x62, 0xe5, 0x33, 0xac, 0x49, 0xd5, 0xbb, 0xab, 0x7c, 0xe4, 0x57,
	0xf0, 0x14, 0x51, 0xa2, 0xe0, 0x65, 0x73, 0x9b, 0xca, 0xac, 0x56, 0x69, 0x2a, 0x34, 0x5d, 0x2b,
	0x2e, 0x9c, 0xa1, 0xfc, 0x9b, 0x9f, 0xc3, 0x9d, 0xbf, 0x96, 0xf0, 0x61, 0x69, 0xe1, 0x7d, 0x95,
	0xb9, 0xd1, 0x8f, 0x15, 0x17, 0xd1, 0xa5, 0xdc, 0x05, 0x93, 0x31, 0xb4, 0x59, 0x61, 0x93, 0x6a,
	0x0f, 0xce, 0x6e, 0xfe, 0xcd, 0x9b, 0xfd, 0x49, 0xfa, 0x85, 0x4d, 0x70, 0x3f, 0x11, 0xb0, 0xe6,
	0x9b, 0xdc, 0xc1, 0x85, 0xe6, 0xe6, 0xc9, 0xe3, 0x6b, 0xef, 0x9b, 0xe9, 0xb9, 0xe6, 0xe6, 0xe9,
	0xb3, 0x13, 0x99, 0xf3, 0x87, 0xd5, 0x2c, 0x96, 0xd9, 0xca, 0x19, 0xf6, 0x24, 0xf2, 0x10, 0x9d,
	0x21, 0x58, 0xee, 0x99, 0xc5, 0x71, 0x39, 0xac, 0x54, 0xad, 0xe8, 0x52, 0xa6, 0x22, 0xf0, 0xf0,
	0x79, 0x22, 0x3c, 0x52, 0xab, 0xa1, 0x4c, 0x05, 0xb9, 0x07, 0x9f, 0x8b, 0x25, 0x2b, 0x52, 0x4b,
	0xb1, 0x93, 0xc0, 0x77, 0x25, 0x75, 0xff, 0xa3, 0xcf, 0x47, 0xff, 0xe0, 0xc8, 0xab, 0x94, 0x78,
	0xec, 0xfe, 0x02, 0x97, 0x3b, 0xe7, 0x4b, 0x8e, 0xe1, 0xc5, 0xfb, 0xe1, 0xb0, 0xf3, 0x8c, 0xb4,
	0xe1, 0xf8, 0xf6, 0x6e, 0xd8, 0x9f, 0x8f, 0x66, 0x9d, 0x16, 0x01, 0x38, 0x9a, 0xce, 0xa2, 0xfb,
	0xc1, 0xac, 0xf3, 0xbc, 0xfb, 0x1a, 0xe0, 0x61, 0x6a, 0xe4, 0x04, 0x0e, 0xde, 0xbd, 0x7f, 0x77,
	0xd7, 0x79, 0x46, 0x7c, 0x80, 0xf1, 0x7c, 0x36, 0xef, 0x8f, 0xe8, 0x6c, 0x34, 0xed, 0xb4, 0x16,
	0x47, 0x6e, 0x40, 0x3f, 0xfd, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xb2, 0x2e, 0x11, 0x3f, 0x67, 0x06,
	0x00, 0x00,
}
