// Code generated by protoc-gen-go.
// source: proxy/v1/config/proxy_mesh.proto
// DO NOT EDIT!

package istio_proxy_v1_config

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf1 "github.com/golang/protobuf/ptypes/duration"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ProxyMeshConfig_IngressControllerMode int32

const (
	// Disables Istio ingress controller.
	ProxyMeshConfig_OFF ProxyMeshConfig_IngressControllerMode = 0
	// Istio ingress controller will act on ingress resources that do not
	// contain any annotation or whose annotations match the value
	// specified in the ingress_class parameter described earlier. Use this
	// mode if Istio ingress controller will be the default ingress
	// controller for the entire kubernetes cluster.
	ProxyMeshConfig_DEFAULT ProxyMeshConfig_IngressControllerMode = 1
	// Istio ingress controller will only act on ingress resources whose
	// annotations match the value specified in the ingress_class parameter
	// described earlier. Use this mode if Istio ingress controller will be
	// a secondary ingress controller (e.g., in addition to a
	// cloud-provided ingress controller).
	ProxyMeshConfig_STRICT ProxyMeshConfig_IngressControllerMode = 2
)

var ProxyMeshConfig_IngressControllerMode_name = map[int32]string{
	0: "OFF",
	1: "DEFAULT",
	2: "STRICT",
}
var ProxyMeshConfig_IngressControllerMode_value = map[string]int32{
	"OFF":     0,
	"DEFAULT": 1,
	"STRICT":  2,
}

func (x ProxyMeshConfig_IngressControllerMode) String() string {
	return proto.EnumName(ProxyMeshConfig_IngressControllerMode_name, int32(x))
}
func (ProxyMeshConfig_IngressControllerMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor5, []int{0, 0}
}

type ProxyMeshConfig_AuthPolicy int32

const (
	// Do not encrypt Envoy to Envoy traffic.
	ProxyMeshConfig_NONE ProxyMeshConfig_AuthPolicy = 0
	// Envoy to Envoy traffic is wrapped into mutual TLS connections.
	ProxyMeshConfig_MUTUAL_TLS ProxyMeshConfig_AuthPolicy = 1
)

var ProxyMeshConfig_AuthPolicy_name = map[int32]string{
	0: "NONE",
	1: "MUTUAL_TLS",
}
var ProxyMeshConfig_AuthPolicy_value = map[string]int32{
	"NONE":       0,
	"MUTUAL_TLS": 1,
}

func (x ProxyMeshConfig_AuthPolicy) String() string {
	return proto.EnumName(ProxyMeshConfig_AuthPolicy_name, int32(x))
}
func (ProxyMeshConfig_AuthPolicy) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor5, []int{0, 1}
}

// ProxyMeshConfig defines variables shared by all Envoy instances in the
// Istio service mesh.
type ProxyMeshConfig struct {
	// Address of the egress Envoy service (e.g. _istio-egress:80_).
	EgressProxyAddress string `protobuf:"bytes,1,opt,name=egress_proxy_address,json=egressProxyAddress" json:"egress_proxy_address,omitempty"`
	// Address of the discovery service exposing SDS, CDS, RDS (e.g. _istio-manager:8080_).
	DiscoveryAddress string `protobuf:"bytes,2,opt,name=discovery_address,json=discoveryAddress" json:"discovery_address,omitempty"`
	// Address of the mixer service (e.g. _istio-mixer:9090_).
	MixerAddress string `protobuf:"bytes,3,opt,name=mixer_address,json=mixerAddress" json:"mixer_address,omitempty"`
	// Address of the Zipkin service (e.g. _zipkin:9411_).
	ZipkinAddress string `protobuf:"bytes,4,opt,name=zipkin_address,json=zipkinAddress" json:"zipkin_address,omitempty"`
	// IP Address and Port of a statsd UDP listener (e.g. _10.75.241.127:9125_).
	StatsdUdpAddress string `protobuf:"bytes,12,opt,name=statsd_udp_address,json=statsdUdpAddress" json:"statsd_udp_address,omitempty"`
	// Port on which Envoy should listen for incoming connections from
	// other services.
	ProxyListenPort int32 `protobuf:"varint,5,opt,name=proxy_listen_port,json=proxyListenPort" json:"proxy_listen_port,omitempty"`
	// Port on which Envoy should listen for administrative commands.
	ProxyAdminPort int32 `protobuf:"varint,6,opt,name=proxy_admin_port,json=proxyAdminPort" json:"proxy_admin_port,omitempty"`
	// Port on which Envoy should listen for HTTP PROXY requests if set.
	ProxyHttpPort int32 `protobuf:"varint,16,opt,name=proxy_http_port,json=proxyHttpPort" json:"proxy_http_port,omitempty"`
	// The time in seconds that Envoy will drain connections during a hot
	// restart. MUST be >=1s (e.g., _1s/1m/1h_)
	DrainDuration *google_protobuf1.Duration `protobuf:"bytes,7,opt,name=drain_duration,json=drainDuration" json:"drain_duration,omitempty"`
	// The time in seconds that Envoy will wait before shutting down the
	// parent process during a hot restart. MUST be >=1s (e.g., _1s/1m/1h_).
	// MUST BE greater than _drain_duration_ parameter.
	ParentShutdownDuration *google_protobuf1.Duration `protobuf:"bytes,8,opt,name=parent_shutdown_duration,json=parentShutdownDuration" json:"parent_shutdown_duration,omitempty"`
	// istio_service_cluster defines the name for the service_cluster that is
	// shared by all Envoy instances. This setting corresponds to
	// _--service-cluster_ flag in Envoy.  In a typical Envoy deployment, the
	// _service-cluster_ flag is used to identify the caller, for
	// source-based routing scenarios.
	//
	//
	// Since Istio does not assign a local service/service version to each
	// Envoy instance, the name is same for all of them.  However, the
	// source/caller's identity (e.g., IP address) is encoded in the
	// _--service-node_ flag when launching Envoy.  When the RDS service
	// receives API calls from Envoy, it uses the value of the _service-node_
	// flag to compute routes that are relative to the service instances
	// located at that IP address.
	IstioServiceCluster string `protobuf:"bytes,9,opt,name=istio_service_cluster,json=istioServiceCluster" json:"istio_service_cluster,omitempty"`
	// Polling interval for service discovery. (MUST BE >=1ms)
	DiscoveryRefreshDelay *google_protobuf1.Duration `protobuf:"bytes,10,opt,name=discovery_refresh_delay,json=discoveryRefreshDelay" json:"discovery_refresh_delay,omitempty"`
	// Connection timeout used by Envoy. (MUST BE >=1ms)
	ConnectTimeout *google_protobuf1.Duration `protobuf:"bytes,11,opt,name=connect_timeout,json=connectTimeout" json:"connect_timeout,omitempty"`
	// Kubernetes namespace to be monitored by Istio control plane.
	// This can be a single application namespace (e.g. "bookinfo") or
	// left unspecified, in which case all Kubernetes namespaces are
	// observed.
	ApplicationNamespace string `protobuf:"bytes,13,opt,name=application_namespace,json=applicationNamespace" json:"application_namespace,omitempty"`
	// File address for the proxy access log (e.g. /dev/stdout)
	AccessLogFile string `protobuf:"bytes,14,opt,name=access_log_file,json=accessLogFile" json:"access_log_file,omitempty"`
	// File address for the proxy error and debug log (e.g. /dev/stderr)
	ErrorLogFile string `protobuf:"bytes,15,opt,name=error_log_file,json=errorLogFile" json:"error_log_file,omitempty"`
	// Class of ingress resources to be processed by Istio ingress
	// controller.  This corresponds to the value of
	// "kubernetes.io/ingress.class" annotation.
	IngressClass string `protobuf:"bytes,20,opt,name=ingress_class,json=ingressClass" json:"ingress_class,omitempty"`
	// Name of the kubernetes service used for the istio ingress controller.
	IngressService string `protobuf:"bytes,21,opt,name=ingress_service,json=ingressService" json:"ingress_service,omitempty"`
	// Defines whether to use Istio ingress controller for annotated or all ingress resources.
	IngressControllerMode ProxyMeshConfig_IngressControllerMode `protobuf:"varint,22,opt,name=ingress_controller_mode,json=ingressControllerMode,enum=istio.proxy.v1.config.ProxyMeshConfig_IngressControllerMode" json:"ingress_controller_mode,omitempty"`
	// Authentication policy defines the global switch to control authentication
	// for Envoy-to-Envoy communication.
	AuthPolicy ProxyMeshConfig_AuthPolicy `protobuf:"varint,100,opt,name=auth_policy,json=authPolicy,enum=istio.proxy.v1.config.ProxyMeshConfig_AuthPolicy" json:"auth_policy,omitempty"`
	// Path to the secrets used by the authentication policy.
	AuthCertsPath string `protobuf:"bytes,101,opt,name=auth_certs_path,json=authCertsPath" json:"auth_certs_path,omitempty"`
}

func (m *ProxyMeshConfig) Reset()                    { *m = ProxyMeshConfig{} }
func (m *ProxyMeshConfig) String() string            { return proto.CompactTextString(m) }
func (*ProxyMeshConfig) ProtoMessage()               {}
func (*ProxyMeshConfig) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{0} }

func (m *ProxyMeshConfig) GetEgressProxyAddress() string {
	if m != nil {
		return m.EgressProxyAddress
	}
	return ""
}

func (m *ProxyMeshConfig) GetDiscoveryAddress() string {
	if m != nil {
		return m.DiscoveryAddress
	}
	return ""
}

func (m *ProxyMeshConfig) GetMixerAddress() string {
	if m != nil {
		return m.MixerAddress
	}
	return ""
}

func (m *ProxyMeshConfig) GetZipkinAddress() string {
	if m != nil {
		return m.ZipkinAddress
	}
	return ""
}

func (m *ProxyMeshConfig) GetStatsdUdpAddress() string {
	if m != nil {
		return m.StatsdUdpAddress
	}
	return ""
}

func (m *ProxyMeshConfig) GetProxyListenPort() int32 {
	if m != nil {
		return m.ProxyListenPort
	}
	return 0
}

func (m *ProxyMeshConfig) GetProxyAdminPort() int32 {
	if m != nil {
		return m.ProxyAdminPort
	}
	return 0
}

func (m *ProxyMeshConfig) GetProxyHttpPort() int32 {
	if m != nil {
		return m.ProxyHttpPort
	}
	return 0
}

func (m *ProxyMeshConfig) GetDrainDuration() *google_protobuf1.Duration {
	if m != nil {
		return m.DrainDuration
	}
	return nil
}

func (m *ProxyMeshConfig) GetParentShutdownDuration() *google_protobuf1.Duration {
	if m != nil {
		return m.ParentShutdownDuration
	}
	return nil
}

func (m *ProxyMeshConfig) GetIstioServiceCluster() string {
	if m != nil {
		return m.IstioServiceCluster
	}
	return ""
}

func (m *ProxyMeshConfig) GetDiscoveryRefreshDelay() *google_protobuf1.Duration {
	if m != nil {
		return m.DiscoveryRefreshDelay
	}
	return nil
}

func (m *ProxyMeshConfig) GetConnectTimeout() *google_protobuf1.Duration {
	if m != nil {
		return m.ConnectTimeout
	}
	return nil
}

func (m *ProxyMeshConfig) GetApplicationNamespace() string {
	if m != nil {
		return m.ApplicationNamespace
	}
	return ""
}

func (m *ProxyMeshConfig) GetAccessLogFile() string {
	if m != nil {
		return m.AccessLogFile
	}
	return ""
}

func (m *ProxyMeshConfig) GetErrorLogFile() string {
	if m != nil {
		return m.ErrorLogFile
	}
	return ""
}

func (m *ProxyMeshConfig) GetIngressClass() string {
	if m != nil {
		return m.IngressClass
	}
	return ""
}

func (m *ProxyMeshConfig) GetIngressService() string {
	if m != nil {
		return m.IngressService
	}
	return ""
}

func (m *ProxyMeshConfig) GetIngressControllerMode() ProxyMeshConfig_IngressControllerMode {
	if m != nil {
		return m.IngressControllerMode
	}
	return ProxyMeshConfig_OFF
}

func (m *ProxyMeshConfig) GetAuthPolicy() ProxyMeshConfig_AuthPolicy {
	if m != nil {
		return m.AuthPolicy
	}
	return ProxyMeshConfig_NONE
}

func (m *ProxyMeshConfig) GetAuthCertsPath() string {
	if m != nil {
		return m.AuthCertsPath
	}
	return ""
}

func init() {
	proto.RegisterType((*ProxyMeshConfig)(nil), "istio.proxy.v1.config.ProxyMeshConfig")
	proto.RegisterEnum("istio.proxy.v1.config.ProxyMeshConfig_IngressControllerMode", ProxyMeshConfig_IngressControllerMode_name, ProxyMeshConfig_IngressControllerMode_value)
	proto.RegisterEnum("istio.proxy.v1.config.ProxyMeshConfig_AuthPolicy", ProxyMeshConfig_AuthPolicy_name, ProxyMeshConfig_AuthPolicy_value)
}

func init() { proto.RegisterFile("proxy/v1/config/proxy_mesh.proto", fileDescriptor5) }

var fileDescriptor5 = []byte{
	// 681 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0x5f, 0x4f, 0xdb, 0x3a,
	0x18, 0xc6, 0x29, 0xff, 0x79, 0x4b, 0xd3, 0xe0, 0x43, 0x21, 0xe7, 0x5c, 0x1c, 0x55, 0x70, 0x0e,
	0xa7, 0x3a, 0x9b, 0xd2, 0x01, 0x57, 0x93, 0x76, 0xb1, 0xae, 0x50, 0x0d, 0xa9, 0x40, 0x97, 0xb6,
	0xd7, 0x96, 0x49, 0xdc, 0xc6, 0x5a, 0x1a, 0x5b, 0xb6, 0xd3, 0xc1, 0x3e, 0xf5, 0x3e, 0xc2, 0x14,
	0x3b, 0x49, 0xd1, 0x84, 0xc4, 0xee, 0xe2, 0xe7, 0xf9, 0x3d, 0xef, 0x1b, 0xdb, 0xaf, 0xa1, 0x2d,
	0x24, 0x7f, 0x7c, 0xea, 0x2e, 0xcf, 0xbb, 0x21, 0x4f, 0x67, 0x6c, 0xde, 0x35, 0x6b, 0xbc, 0xa0,
	0x2a, 0xf6, 0x85, 0xe4, 0x9a, 0xa3, 0x16, 0x53, 0x9a, 0x71, 0xdf, 0xe8, 0xfe, 0xf2, 0xdc, 0xb7,
	0xdc, 0x5f, 0x7f, 0xcf, 0x39, 0x9f, 0x27, 0xb4, 0x6b, 0xa0, 0x87, 0x6c, 0xd6, 0x8d, 0x32, 0x49,
	0x34, 0xe3, 0xa9, 0x8d, 0x9d, 0xfc, 0xd8, 0x83, 0xe6, 0x28, 0xcf, 0xdc, 0x52, 0x15, 0xf7, 0x4d,
	0x06, 0xbd, 0x83, 0x43, 0x3a, 0x97, 0x54, 0x29, 0x6c, 0xbb, 0x90, 0x28, 0xca, 0x57, 0x5e, 0xad,
	0x5d, 0xeb, 0xec, 0x05, 0xc8, 0x7a, 0x26, 0xd4, 0xb3, 0x0e, 0x7a, 0x03, 0x07, 0x11, 0x53, 0x21,
	0x5f, 0x52, 0xb9, 0xc2, 0xd7, 0x0d, 0xee, 0x56, 0x46, 0x09, 0x9f, 0x42, 0x63, 0xc1, 0x1e, 0xa9,
	0xac, 0xc0, 0x0d, 0x03, 0xee, 0x1b, 0xb1, 0x84, 0xfe, 0x05, 0xe7, 0x3b, 0x13, 0x5f, 0x59, 0x5a,
	0x51, 0x9b, 0x86, 0x6a, 0x58, 0xb5, 0xc4, 0xde, 0x02, 0x52, 0x9a, 0x68, 0x15, 0xe1, 0x2c, 0x12,
	0x15, 0xba, 0x6f, 0x3b, 0x5b, 0x67, 0x1a, 0x89, 0x92, 0xfe, 0x1f, 0x0e, 0xec, 0x8e, 0x12, 0xa6,
	0x34, 0x4d, 0xb1, 0xe0, 0x52, 0x7b, 0x5b, 0xed, 0x5a, 0x67, 0x2b, 0x68, 0x1a, 0x63, 0x68, 0xf4,
	0x11, 0x97, 0x1a, 0x75, 0xc0, 0x2d, 0x77, 0xbf, 0x60, 0x05, 0xba, 0x6d, 0x50, 0x47, 0xd8, 0xad,
	0x2f, 0x98, 0x25, 0xcf, 0xc0, 0x86, 0x71, 0xac, 0xb5, 0xb0, 0xa0, 0x6b, 0xc0, 0x86, 0x91, 0x3f,
	0x6b, 0x2d, 0x0c, 0xf7, 0x11, 0x9c, 0x48, 0x12, 0x96, 0xe2, 0xf2, 0x0a, 0xbc, 0x9d, 0x76, 0xad,
	0x53, 0xbf, 0xf8, 0xd3, 0xb7, 0x77, 0xe4, 0x97, 0x77, 0xe4, 0x5f, 0x15, 0x40, 0xd0, 0x30, 0x81,
	0x72, 0x89, 0xc6, 0xe0, 0x09, 0x22, 0x69, 0xaa, 0xb1, 0x8a, 0x33, 0x1d, 0xf1, 0x6f, 0xcf, 0x6a,
	0xed, 0xbe, 0x56, 0xeb, 0xc8, 0x46, 0xc7, 0x45, 0xb2, 0x2a, 0x7a, 0x01, 0x76, 0x74, 0xb0, 0xa2,
	0x72, 0xc9, 0x42, 0x8a, 0xc3, 0x24, 0x53, 0x9a, 0x4a, 0x6f, 0xcf, 0x9c, 0xe2, 0x1f, 0xc6, 0x1c,
	0x5b, 0xaf, 0x6f, 0x2d, 0xf4, 0x05, 0x8e, 0x57, 0xf7, 0x2d, 0xe9, 0x4c, 0x52, 0x15, 0xe3, 0x88,
	0x26, 0xe4, 0xc9, 0x83, 0xd7, 0xfe, 0xa3, 0x55, 0x25, 0x03, 0x1b, 0xbc, 0xca, 0x73, 0xe8, 0x13,
	0x34, 0x43, 0x9e, 0xa6, 0x34, 0xd4, 0x58, 0xb3, 0x05, 0xe5, 0x99, 0xf6, 0xea, 0xaf, 0x95, 0x72,
	0x8a, 0xc4, 0xc4, 0x06, 0xd0, 0x25, 0xb4, 0x88, 0x10, 0x09, 0x0b, 0x8d, 0x8d, 0x53, 0xb2, 0xa0,
	0x4a, 0x90, 0x90, 0x7a, 0x0d, 0xb3, 0x95, 0xc3, 0x67, 0xe6, 0x5d, 0xe9, 0xe5, 0xd7, 0x47, 0xc2,
	0x30, 0x9f, 0xf6, 0x84, 0xcf, 0xf1, 0x8c, 0x25, 0xd4, 0x73, 0xec, 0xa8, 0x59, 0x79, 0xc8, 0xe7,
	0x03, 0x96, 0x50, 0xf4, 0x0f, 0x38, 0x54, 0x4a, 0x2e, 0x57, 0x58, 0xd3, 0xce, 0xad, 0x51, 0x4b,
	0xea, 0x14, 0x1a, 0x2c, 0xb5, 0x8f, 0x27, 0x4c, 0x88, 0x52, 0xde, 0xa1, 0x85, 0x0a, 0xb1, 0x9f,
	0x6b, 0xe8, 0x3f, 0x68, 0x96, 0x50, 0x71, 0xe8, 0x5e, 0xcb, 0x60, 0x4e, 0x21, 0x17, 0xc7, 0x8d,
	0x34, 0x1c, 0x57, 0xd5, 0x78, 0xaa, 0x25, 0x4f, 0x12, 0x2a, 0xf1, 0x82, 0x47, 0xd4, 0x3b, 0x6a,
	0xd7, 0x3a, 0xce, 0xc5, 0x07, 0xff, 0xc5, 0x67, 0xef, 0xff, 0xf2, 0xa4, 0xfd, 0x9b, 0xa2, 0x7d,
	0x55, 0xe4, 0x96, 0x47, 0x34, 0x68, 0xb1, 0x97, 0x64, 0x14, 0x40, 0x9d, 0x64, 0x3a, 0xc6, 0x82,
	0x27, 0x2c, 0x7c, 0xf2, 0x22, 0xd3, 0xe9, 0xfc, 0x37, 0x3b, 0xf5, 0x32, 0x1d, 0x8f, 0x4c, 0x30,
	0x00, 0x52, 0x7d, 0x9b, 0x53, 0xce, 0x6b, 0x86, 0x54, 0x6a, 0x85, 0x05, 0xd1, 0xb1, 0x47, 0x8b,
	0x53, 0xce, 0x74, 0xdc, 0xcf, 0xd5, 0x11, 0xd1, 0xf1, 0xc9, 0x7b, 0x68, 0xbd, 0xf8, 0xaf, 0x68,
	0x07, 0x36, 0xee, 0x07, 0x03, 0x77, 0x0d, 0xd5, 0x61, 0xe7, 0xea, 0x7a, 0xd0, 0x9b, 0x0e, 0x27,
	0x6e, 0x0d, 0x01, 0x6c, 0x8f, 0x27, 0xc1, 0x4d, 0x7f, 0xe2, 0xae, 0x9f, 0x9c, 0x01, 0xac, 0x9a,
	0xa3, 0x5d, 0xd8, 0xbc, 0xbb, 0xbf, 0xbb, 0x76, 0xd7, 0x90, 0x03, 0x70, 0x3b, 0x9d, 0x4c, 0x7b,
	0x43, 0x3c, 0x19, 0x8e, 0xdd, 0xda, 0xc3, 0xb6, 0x19, 0xa4, 0xcb, 0x9f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x94, 0xa9, 0xad, 0x8b, 0x54, 0x05, 0x00, 0x00,
}
